#!/bin/bash
# Clone/update bare git mirrors needed by test_cve_corrector.sh into MIRROR_DIR.
set -euo pipefail

MIRROR_DIR="${MIRROR_DIR:-${HOME}/git}"
mkdir -p "$MIRROR_DIR"

log() { echo "[$(date +%H:%M:%S)] $*"; }

# name -> upstream clone URL
declare -A MIRRORS=(
    [abseil-cpp]="https://github.com/abseil/abseil-cpp"
    [acpica]="https://github.com/acpica/acpica"
    [alsa-lib]="https://github.com/alsa-project/alsa-lib"
    [avahi]="https://github.com/lathiat/avahi"
    [binutils]="https://github.com/bminor/binutils-gdb"
    [busybox]="https://github.com/mirror/busybox"
    [cairo]="https://gitlab.freedesktop.org/cairo/cairo"
    [certifi]="https://github.com/certifi/python-certifi"
    [cmake]="https://gitlab.kitware.com/cmake/cmake"
    [connman]="https://git.kernel.org/pub/scm/network/connman/connman.git"
    [coreutils]="https://github.com/coreutils/coreutils"
    [cpython]="https://github.com/python/cpython"
    [cryptography]="https://github.com/pyca/cryptography"
    [cups]="https://github.com/OpenPrinting/cups"
    [curl]="https://github.com/curl/curl"
    [dpkg]="https://git.dpkg.org/git/dpkg/dpkg.git"
    [dropbear]="https://github.com/mkj/dropbear"
    [elfutils]="https://sourceware.org/git/elfutils.git"
    [expat]="https://github.com/libexpat/libexpat"
    [fio]="https://github.com/axboe/fio"
    [freetype]="https://gitlab.freedesktop.org/freetype/freetype"
    [gdk-pixbuf]="https://gitlab.gnome.org/GNOME/gdk-pixbuf"
    [ghostscript]="https://github.com/ArtifexSoftware/ghostpdl"
    [gi-docgen]="https://gitlab.gnome.org/GNOME/gi-docgen"
    [glib]="https://gitlab.gnome.org/GNOME/glib"
    [glib-networking]="https://gitlab.gnome.org/GNOME/glib-networking"
    [gnupg]="https://github.com/gpg/gnupg"
    [gnutls]="https://gitlab.com/gnutls/gnutls"
    [go]="https://github.com/golang/go"
    [grpc]="https://github.com/grpc/grpc"
    [grub2]="https://git.savannah.gnu.org/git/grub.git"
    [gst-plugins-bad]="https://gitlab.freedesktop.org/gstreamer/gstreamer"
    [gst-plugins-base]="https://gitlab.freedesktop.org/gstreamer/gstreamer"
    [gst-plugins-good]="https://gitlab.freedesktop.org/gstreamer/gstreamer"
    [harfbuzz]="https://github.com/harfbuzz/harfbuzz"
    [hostap]="https://w1.fi/hostap.git"
    [icu]="https://github.com/unicode-org/icu"
    [inetutils]="https://codeberg.org/inetutils/inetutils"
    [iperf3]="https://github.com/esnet/iperf"
    [iputils]="https://github.com/iputils/iputils"
    [jq]="https://github.com/jqlang/jq"
    [less]="https://github.com/gwsw/less"
    [libarchive]="https://github.com/libarchive/libarchive"
    [libblockdev]="https://github.com/storaged-project/libblockdev"
    [libcap]="https://git.kernel.org/pub/scm/libs/libcap/libcap.git"
    [libpcap]="https://github.com/the-tcpdump-group/libpcap"
    [libpng]="https://github.com/pnggroup/libpng"
    [libsndfile]="https://github.com/libsndfile/libsndfile"
    [libsodium]="https://github.com/jedisct1/libsodium"
    [libsoup]="https://gitlab.gnome.org/GNOME/libsoup"
    [libssh]="https://git.libssh.org/projects/libssh.git"
    [libtasn1]="https://gitlab.com/gnutls/libtasn1"
    [libxml2]="https://github.com/GNOME/libxml2"
    [libxslt]="https://gitlab.gnome.org/GNOME/libxslt"
    [linux-pam]="https://github.com/linux-pam/linux-pam"
    [llvm-project]="https://github.com/llvm/llvm-project"
    [lz4]="https://github.com/lz4/lz4"
    [ncurses]="https://github.com/mirror/ncurses"
    [net-snmp]="https://github.com/net-snmp/net-snmp"
    [nghttp2]="https://github.com/nghttp2/nghttp2"
    [openssh]="https://github.com/openssh/openssh-portable"
    [openssl]="https://github.com/openssl/openssl"
    [patch]="https://git.savannah.gnu.org/git/patch.git"
    [perl]="https://github.com/Perl/perl5"
    [pip]="https://github.com/pypa/pip"
    [ppp]="https://github.com/ppp-project/ppp"
    [pyasn1]="https://github.com/pyasn1/pyasn1"
    [pyopenssl]="https://github.com/pyca/pyopenssl"
    [python3-setuptools]="https://github.com/pypa/setuptools"
    [qemu]="https://github.com/qemu/qemu"
    [re2c]="https://github.com/skvadrik/re2c"
    [rsync]="https://github.com/RsyncProject/rsync"
    [screen]="https://git.savannah.gnu.org/git/screen.git"
    [sqlite3]="https://github.com/sqlite/sqlite"
    [strongswan]="https://github.com/strongswan/strongswan"
    [subversion]="https://github.com/apache/subversion"
    [sudo]="https://github.com/sudo-project/sudo"
    [tar]="https://git.savannah.gnu.org/git/tar.git"
    [tcpdump]="https://github.com/the-tcpdump-group/tcpdump"
    [tiff]="https://gitlab.com/libtiff/libtiff"
    [u-boot-tools]="https://source.denx.de/u-boot/u-boot"
    [unzip]="https://github.com/madler/unzip"
    [urllib3]="https://github.com/urllib3/urllib3"
    [util-linux]="https://github.com/util-linux/util-linux"
    [vim]="https://github.com/vim/vim"
    [vte]="https://gitlab.gnome.org/GNOME/vte"
    [wget]="https://git.savannah.gnu.org/git/wget.git"
    [wheel]="https://github.com/pypa/wheel"
    [xmltodict]="https://github.com/martinblech/xmltodict"
    [xserver]="https://gitlab.freedesktop.org/xorg/xserver"
    [xz]="https://github.com/tukaani-project/xz"
    [zipp]="https://github.com/jaraco/zipp"
    [zlib]="https://github.com/madler/zlib"
)

ok=0; fail=0
for name in $(printf '%s\n' "${!MIRRORS[@]}" | grep -v '^busybox$' | sort; echo busybox); do
    url="${MIRRORS[$name]}"
    dest="$MIRROR_DIR/$name"
    if [[ -d "$dest" ]]; then
        log "Updating $name..."
        git -C "$dest" remote update --prune && ok=$((ok+1)) || { log "WARN: update failed for $name"; fail=$((fail+1)); }
    else
        log "Cloning $name from $url..."
        git clone --bare "$url" "$dest" && ok=$((ok+1)) || { log "WARN: clone failed for $name"; fail=$((fail+1)); }
    fi
done

log "Done: $ok succeeded, $fail failed"
